### PR TITLE
Add API to register custom "can fly checks"

### LINKED ISSUE #13: Allow overriding `can_fly` function
Could be used to block flying for any number of reasons, but one use case would be to block flying in space: https://github.com/pandorabox-io/in-game/issues/117

### PR DESCRIPTION
**Pull request by Niklp09**
Closes https://github.com/mt-mods/hangglider/issues/13

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]
lgtm (didn't check for perf issues if multiple mods would resolve a player from name in the callback though, shouldn't be much i think :shrug:)

**Comment by OgelGames** [comment]
Yeah performance issues was one thought I had, that's why I opened an issue instead of implementing it immediately.

Also, the `can_fly` function is currently used for area flak, extra code needs to be added that prevents glider use without shooting you down.

**Comment by Niklp09** [comment]
> if multiple mods would resolve a player from name in the callback though

The function passes now `name` and `player`

> the can_fly function is currently used for area flak [too]

Fixed.

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by OgelGames** [comment]
Oh I forgot about this one... Still not quite complete yet I think, I'll do some tests tomorrow.

**Comment by SwissalpS** [comment]
LGTM. I'm not stocked about the naming of ``can_fly_area`` but there is no perfect name, so fine by me. ``can_fly_flak`` might be a bit more precise as area is a mod but also well, an area.

**Comment by SwissalpS** [comment]
In another glider mod I'm going for this approach:

```lua
-- Allow other mods to register custom flight checks
-- to disallow flying in certain areas or materials
-- such as on the moon or without priv in certain area
-- The function's signature is: (name, driver, luaent)
-- name: (string) player's name
-- driver: (PlayerObjRef) the player object
-- luaent: (nil or luaentity) the glider luaentity. When set,
--   player is already flying. When not, player would like to
--   take off.
-- The function must return true to indicate that player may
-- fly. A second return value of int may be provided to
-- indicate damage to player from which damage to glider
-- is also applied. Sensible values are from -20 to 20.
-- Negative meaning healing.
local flight_checks = {}
function glider.register_flight_check(func)
	flight_checks[#flight_checks + 1] = func
end

local function custum_flight_checks(name, driver, luaent)
	local i = #flight_checks
	if i == 0 then
		return true, 0
	end

	local has_fails = false
	local damage = 0
	local res_bool, res_int
	repeat
		res_bool, res_int = flight_checks[i](name, driver, luaent)
		if not res_bool then
			has_fails = true
		end
		if type(res_int) == "number" then
			damage = damage + math_max(-20, math_min(20, res_int))
		end
		i = i - 1
	until i == 0
	return not has_fails, damage
end
```

Allowing mods to cause damage to glider cumulative and also allowing them to manipulate the luaentity.

I also hope to extend the ``can_fly_flak()`` method to  include area_xp and area_priv settings and not only ownership of area.

Edit: in this mod, damage to glider isn't that interesting and damage to player can be done directly to player object. What I'm pointing out, is the cumulative effect.

**Comment by Niklp09** [comment]
@OgelGames Rebased on master.

**Pull request closed without merging**
