### PR TITLE
Hangglider rewrite and improvements

### PR DESCRIPTION
**Pull request by OgelGames**
Completely refactors the code for readability, and adds some improvements:

- Fixed flying upwards by limiting antigravity and using `player:add_velocity` as an airbrake when falling too fast.
- The hangglider now prevents all fall damage while it is open.
- Damaging liquids (e.g. lava) are no longer considered a safe node to land on.
- Added settings to enable flak, enable the hud, and change the number of uses.
- Added recipe to repair the hangglider with wool.
- Added coloring recipe for up to 256 colors of hangglider (if `unifieddyes is installed)
- Changed file names of media to comply with the `modname_*` naming convention, and optimized textures.
- Removed `hangglider` global variable.
- Added README.md, and description to mod.conf.

### CODE REVIEW

**Comment by SwissalpS** [comment]
colour-able gliders? (ducks)

**Comment by OgelGames** [comment]
> colour-able gliders? (ducks)

Hmm... I think that might be possible :thinking:

**Comment by SwissalpS** [comment]
with the cover overlay feature, I have coloured glider items in inventory (made using replacer) that way it wouldn't need new items for every colour.

**Comment by OgelGames** [comment]
I did one better, up to 256 colors of hangglider with only one recipe and one item :D

image

Yeah, it might be a bit overkill, but why not :)

**Comment by Athozus** [comment]
LGTM :+1:

**Review by BuckarooBanzay — APPROVED** [review]
nice :tada:

**Review by Niklp09 — APPROVED** [review]
LGTM

**Pull request merged**
