### PR TITLE
partially fixes #1

### LINKED ISSUE #1: Undeclared global variables (4) during game and usage
```
2021-04-23 08:25:54: WARNING[Server]: Undeclared global variable "player_monoids" accessed at /home/thomas/.minetest/mods/hangglider/init.lua:182
2021-04-23 08:25:54: WARNING[Server]: Undeclared global variable "minetestd" accessed at /home/thomas/.minetest/mods/hangglider/init.lua:227
2021-04-23 08:25:54: WARNING[Server]: Undeclared global variable "wardzones" accessed at /home/thomas/.minetest/mods/hangglider/init.lua:149
2021-04-23 08:26:08: WARNING[Server]: Undeclared global variable "minetestd" accessed at /home/thomas/.minetest/mods/hangglider/init.lua:261
```

at Minetest Server Asia thailand

### PR DESCRIPTION
**Pull request by Niklp09**
#1 
no idea what "wardzones" is supposed to be, it doesn't seem to be a mod

### CODE REVIEW

**Comment by wsor4035** [comment]
its a mod by Piezo: https://notabug.org/Piezo_ but doesnt seem to be available anymore?

**Comment by wsor4035** [comment]
forum post with dead link to it https://forum.minetest.net/viewtopic.php?p=342927#p342927

**Comment by Niklp09** [comment]
Should I remove the wardzones support?

**Comment by wsor4035** [comment]
it seems to be a protection like mod by the orginal author of this mod. addtionally, no servers seem to use it all. looking at minetest systemd, it seems only one server on the list actually uses it, and it is another mod by the original author.

link: https://notabug.org/Piezo_/minetest_systemd

personally i would drop both, as no one seems to actually seriously use either of them (the one server with it appears to use it as a dep for some other mod, not its actual intended use globally - unless they forked a lot of mods)

**Review by wsor4035 — APPROVED** [review]

**Comment by BuckarooBanzay** [comment]
> personally i would drop both, as no one seems to actually seriously use either of them (the one server with it appears to use it as a dep for some other mod, not its actual intended use globally - unless they forked a lot of mods)

fine with me too (it just got merged :ninja:)

**Pull request merged**
